# Generated by Django 4.0.6 on 2022-07-08 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimrecord',
            name='last_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
