# Generated by Django 4.0.6 on 2022-07-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0002_swimrecord_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimrecord',
            name='relay',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='team_name',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
