# Generated by Django 4.0.6 on 2022-07-08 03:01

import django.core.validators
from django.db import migrations, models
import swimrecords.models


class Migration(migrations.Migration):

    dependencies = [
        ('swimrecords', '0003_swimrecord_relay_swimrecord_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='swimrecord',
            name='distance',
            field=models.IntegerField(default=None, validators=[django.core.validators.MinValueValidator(50)]),
        ),
        migrations.AddField(
            model_name='swimrecord',
            name='stroke',
            field=models.CharField(default=None, max_length=255, validators=[swimrecords.models.validate_stroke]),
        ),
        migrations.AlterField(
            model_name='swimrecord',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
